version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase

  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
